### ISSUE TITLE
cannot complete order

### ISSUE THREAD

**Issue by CreamyG31337** [firebearstudio/shapeshift-magento2#10]
After clicking 'place order' I am not redirected to Shape Shift to make the payment. Instead, it gives a spinning progress indicator for a few seconds, then a blank error:
![image](https://user-images.githubusercontent.com/11222932/39669347-6c3f00a0-50a6-11e8-9a53-c0cd09a4734e.png)

The log doesn't show anything to tell me what's wrong either:
```
[2018-05-06 02:46:01] main.INFO: API START [] []
[2018-05-06 02:46:02] main.INFO: SELECT CURRENCY NAME: Litecoin [] []
[2018-05-06 02:46:03] main.INFO: DEPOSIT ADDRESS: LfEM5mhtRYVsemV16G3xaM55hH5WZg2uUW [] []
[2018-05-06 02:46:03] main.INFO: RETURN ADDRESS:  [] []
[2018-05-06 02:46:03] main.INFO: AMOUNT: 0.0557289345 [] []
[2018-05-06 02:46:03] main.INFO: API XCHECK DEFAULT [] []
[2018-05-06 02:46:03] main.INFO: API XCHECK AMOUNT [] []
[2018-05-06 02:46:03] main.INFO: sendFixedAmount() 1 [] []
[2018-05-06 02:46:03] main.INFO: sendFixedAmount() 2 [] []
[2018-05-06 02:46:03] main.INFO: sendFixedAmount() 3 [] []
[2018-05-06 02:46:21] main.INFO: sendFixedAmount() DATA:  {"success":{"orderId":"7d4ac5ce-e595-4080-ba83-8d262cce6c46","pair":"eth_ltc","withdrawal":"LfEM5mhtRYVsemV16G3xaM55hH5WZg2uUW","withdrawalAmount":"0.0557289345","deposit":"0x8ea24bd7de96e74cba59ab7b4d52432f3a893463","depositAmount":"0.0123313","expiration":1525575381542,"quotedRate":"4.58012726","maxLimit":6.01255456,"returnAddress":"","apiPubKey":"2106861f10516dabde38412e6568a11890605ccea018377daf8fa4378eeed12f33a7b73bda9ed23250fbbedf939e5101be80218746ac97edca6ab96516d92f73","minerFee":"0.00075"}} []
```

Order goes through fine if I choose a different payment method.
Magento v2.2.3

**Comment by biotech** [comment]
Thanks for all reports, we will research and get back to you soon, all will be fixed asap

**Comment by CreamyG31337** [comment]
Thanks! I also set magento to developer mode but no additional message was shown. I'll try the coinpayments module in the next day or so -- hoping for better luck with that one. Having two choices for the checkout would be really good though!

**Comment by CreamyG31337** [comment]
found some errors logs in /var/report/api related to this:
`
"Fatal Error: 'Uncaught Error: Call to a member function getEmail() on null in \/var\/www\/zzz.shop\/public_html\/vendor\/firebear\/shapeshift\/Gateway\/Request\/AuthorizationRequest.php:53\nStack trace:\n#0 \/var\/www\/zzz.shop\/public_html\/vendor\/magento\/module-payment\/Gateway\/Request\/BuilderComposite.php(50): Firebear\\ShapeShift\\Gateway\\Request\\AuthorizationRequest->build(Array)\n#1 \/var\/www\/zzz.shop\/public_html\/vendor\/magento\/module-payment\/Gateway\/Command\/GatewayCommand.php(99): Magento\\Payment\\Gateway\\Request\\BuilderComposite->build(Array)\n#2 \/var\/www\/zzz.shop\/public_html\/vendor\/magento\/module-payment\/Model\/Method\/Adapter.php(546): Magento\\Payment\\Gateway\\Command\\GatewayCommand->execute(Array)\n#3 \/var\/www\/zzz.shop\/public_html\/vendor\/magento\/module-payment\/Model\/Method\/Adapter.php(448): Magento\\Payment\\Model\\Method\\Adapter->executeCommand('authorize', Array)\n#4 \/var\/www\/zzz.shop\/public_html\/vendor\/magento\/module-sales\/Model\/Order\/Payment\/Operations\/AuthorizeOperation.php(45): Magento\\Payment\\Model\\Method\\Adapter' in '\/var\/www\/zzz.shop\/public_html\/vendor\/firebear\/shapeshift\/Gateway\/Request\/AuthorizationRequest.php' on line 53"
`
